// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB9JRwPZJsp8IexDqgHpw-r2_xElEmpz4',
    appId: '1:398685397061:web:087c6139d4c55e7746832c',
    messagingSenderId: '398685397061',
    projectId: 'movie-watchlist-f0a2d',
    authDomain: 'movie-watchlist-f0a2d.firebaseapp.com',
    storageBucket: 'movie-watchlist-f0a2d.firebasestorage.app',
    measurementId: 'G-V3FD3L54NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTeNciXABFliJFPz2PYBsVAUSVeraSOgs',
    appId: '1:398685397061:android:7ec6f6eb5caf7f8f46832c',
    messagingSenderId: '398685397061',
    projectId: 'movie-watchlist-f0a2d',
    storageBucket: 'movie-watchlist-f0a2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSahatGoaUu8Cv1FY3THfRyH5JWbedX0',
    appId: '1:398685397061:ios:fcb1a782c0ed5b3446832c',
    messagingSenderId: '398685397061',
    projectId: 'movie-watchlist-f0a2d',
    storageBucket: 'movie-watchlist-f0a2d.firebasestorage.app',
    iosBundleId: 'com.example.movieWatchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSSahatGoaUu8Cv1FY3THfRyH5JWbedX0',
    appId: '1:398685397061:ios:fcb1a782c0ed5b3446832c',
    messagingSenderId: '398685397061',
    projectId: 'movie-watchlist-f0a2d',
    storageBucket: 'movie-watchlist-f0a2d.firebasestorage.app',
    iosBundleId: 'com.example.movieWatchlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB9JRwPZJsp8IexDqgHpw-r2_xElEmpz4',
    appId: '1:398685397061:web:dddf83822661165546832c',
    messagingSenderId: '398685397061',
    projectId: 'movie-watchlist-f0a2d',
    authDomain: 'movie-watchlist-f0a2d.firebaseapp.com',
    storageBucket: 'movie-watchlist-f0a2d.firebasestorage.app',
    measurementId: 'G-YNGL4YB07S',
  );
}
